### PR TITLE
Abstract operation Architecture Decision Record

### PR DESCRIPTION
**Pull request by mr-c**
Documents current thinking for https://github.com/common-workflow-language/common-workflow-language/issues/337

### CODE REVIEW

**Comment by stain** [comment]
Please help review/edit! [Readable version here](https://github.com/common-workflow-language/common-workflow-language/blob/abstract-operation/design-decisions/operation-2019.md)

**Comment by stain** [comment]
Schema Salad changes for adding `Operation` in common-workflow-language/cwl-v1.2#3 and its implementation in common-workflow-language/cwltool#1218

**Comment by kaushik-work** [comment]
@stain 



## Argument A

Why can this not be achieved by having place holder regular process objects that have and empty list for steps or empty list for base command? I feel this is about the same amount of typing with the advantage that then I can go in and just flesh out the skeleton. This is like when we create program skeletons and do things like 

```
def foo(in1, in2):
  return True
```

and come back later and fill out the stub.


The use case for having multiple tools with the same interface is intriguing but I feel that this is not a compelling use case for me. Related use cases are elegantly handled by the existing typedef system.


## Argument B

What is the behavior of the executor when it encounters this abstract operation. Does it fill out the outputs with nulls? With some random value of the correct type?

Thanks!

**Comment by tetron** [comment]
> The use case for having multiple tools with the same interface is intriguing but I feel that this is not a compelling use case for me.

However, that's the use case that motivated the original proposal.  @stain's use cases focus more on the placeholder aspect, though.  If it is a no-op CommandLineTool you can't programmatically determine if something is a placeholder unless we documented a specific constraints on the CommandLineTool type that made it a placeholder --- but then we might as well define a new record type anyway so it can be typechecked.

> What is the behavior of the executor when it encounters this abstract operation. Does it fill out the outputs with nulls?

Perhaps the upfront static checker should declare it invalid to run.  Or attempting to run the step should fail.  Or, it could be treated like a skipped step and produce nulls.  It's a good question.

**Pull request merged**
