### PR TITLE
Test InitialWorkDirRequirement with a nested directory structure 

### PR DESCRIPTION
**Pull request by mr-c**
from another step

Demonstration of https://github.com/BD2KGenomics/toil/issues/1969

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
Rabix doesn't have this error. Arvados presumably doesn't either. @tetron can I get a review & merge?

**Comment by tetron** [comment]
I have a feeling this will break Arvados because Keep doesn't handle empty directories, but otherwise it looks good to me (it's exactly the sort of edge case the conformance tests should check for).

**Comment by mr-c** [comment]
@tetron :-) Thanks!

**Pull request merged**
