### PR TITLE
Test for using $mixin 

### PR DESCRIPTION
**Pull request by tetron**
In this example, to simplify redundant "inputs:" section in subworkflow.

### CODE REVIEW

**Comment by tetron** [comment]
Note, requires a schema salad fix.

**Comment by karl616** [comment]
I set up a pipeliine today that wished that this problem was solved.
Is there another solution to have something like a global settings file?

**Comment by tom-tan** [comment]
Can we close this issue?
`$mixin` was already removed in [Schema Salad v1.2](https://www.commonwl.org/v1.2/SchemaSalad.html#Introduction_to_v1.1).

**Comment by mr-c** [comment]
Thank you @tom-tan  for catching this!

**Pull request closed without merging**
