### PR TITLE
add .python-version and requirements.txt

### PR DESCRIPTION
**Pull request by slnovak**
Adds `.python-version` and `requirements.txt` to facilitate development and testing.

### CODE REVIEW

**Comment by mr-c** [comment]
@slnovak Thanks. Can you enlightened me as to what tools or standard a `.python-version` file corresponds to? Is this meant to be a minimum required version or something else?

**Comment by mr-c** [comment]
Ah, this is for #112

**Comment by tetron** [comment]
Hi @slnovak I came across this blog post about how to avoid repeating dependencies between setup.py and requirements.txt, what do you think?

https://caremad.io/2013/07/setup-vs-requirement/

**Comment by slnovak** [comment]
Good find!

There's a [good reference](http://stackoverflow.com/questions/14399534/how-can-i-reference-requirements-txt-for-the-install-requires-kwarg-in-setuptool) on SO which shows how you can use PIP's `parse_requirements` to parse through `requirements.txt` for importing requirements into `setup.py`. This might be a better approach for reducing duplicate dependencies.

What do you think about that?

**Comment by mr-c** [comment]
Since the reference implementation is now its own repository I'm going to close this pull request. I agree that is is a good idea! Tracking issue for the new repository is at https://github.com/common-workflow-language/cwltool/issues/5

**Pull request closed without merging**
