### PR TITLE
Oodles of new conformance tests

### PR DESCRIPTION
**Pull request by jmchilton**
There was a bunch of complexity related to simple input and output, default values, optional values, Any, union types, etc... to workflows and tools in Galaxy. This adds a bunch of conformance tests that isolates these basic input and output concerns.

There were also test cases for subworkflow scattering - this adds a couple of those.

### CODE REVIEW

**Comment by jmchilton** [comment]
Added another commit - from commit message:

More subworkflow conformance tests.
- Test twice nested subworkflows.
- Test mixing nested workflows and tools at different depths - tools before and after subworkflows.

This second bullet here actually helped me uncover a very subtle bug for nested workflows in Galaxy independent of CWL - so that is pretty cool.

**Comment by mr-c** [comment]
Jenkins, test this please

**Comment by jmchilton** [comment]
And more tests
- tests for literals in valueFrom steps as well as expressions based on ``basename``
- the basename workflow is also a two step workflow that verifies ``basename`` preservation
- various tests for output arrays in workflows

**Comment by tetron** [comment]
Thanks John!

**Comment by mr-c** [comment]
Thank you @jmchilton ! Lets get someone from team Rabix to review this as they aren't passing there

**Comment by jmchilton** [comment]
Added a test to ensure Docker run works with default ``CMD`` in Docker images. It is quite frustrating that it is supposed to work this way - this really should be an implementation detail, but if it has to work that way we should have a test to confirm it does. https://github.com/common-workflow-language/galaxy/issues/66

**Comment by jmchilton** [comment]
Added more tests stemming from Galaxy bugs - including more basic input/output sort of tests over union types involving ``File``s and some tests to ensure that ``size`` is being populated and made available to ``valueFrom`` expressions in tools.

**Comment by jmchilton** [comment]
Rebased - Arvados and cwltool pass. Rabix errors seem unrelated?

```
/var/lib/jenkins/jobs/cwl-spec-pr/workspace/implementation/rabix/version/v1.0/bunny/rabix-cli-1.0.4/rabix ---
./run_test.sh: line 72: /var/lib/jenkins/jobs/cwl-spec-pr/workspace/implementation/rabix/version/v1.0/bunny/rabix-cli-1.0.3/rabix
/var/lib/jenkins/jobs/cwl-spec-pr/workspace/implementation/rabix/version/v1.0/bunny/rabix-cli-1.0.4/rabix: No such file or directory
```

**Comment by mr-c** [comment]
Jenkins, test this please

**Comment by mr-c** [comment]
Jenkins, test this please

**Pull request merged**
