### PR TITLE
Corrections and test data

### PR DESCRIPTION
**Pull request by denis-yuen**
* fix a bunch of examples where the filenames do not match between provided samples and command-line calls
* provide data for workflows
* fix a reference to JSON when YML is provided
* a typo or two

### CODE REVIEW

**Comment by mr-c** [comment]
Thank you @denis-yuen ! Did you mean to update only the draft-4 user guide? I believe we are only building the draft-3 user guide for the website right now.

**Comment by denis-yuen** [comment]
Not really. 
I was attempting to update the source for http://www.commonwl.org/draft-3/UserGuide.html which is draft-3, but I guess I did draft-4 by accident. I think the changes still apply though.

**Comment by mr-c** [comment]
@denis-yuen Should I open a new PR to add these to the draft-3 user guide or can you update this PR?

**Comment by denis-yuen** [comment]
@mr-c  Give that a shot, I think that handles draft-3 as well

**Comment by mr-c** [comment]
Looks great, thanks!

**Pull request merged**
