### PR TITLE
test for POSIX glob behavior

### PR DESCRIPTION
**Pull request by mr-c**
Tests https://github.com/common-workflow-language/cwltool/pull/587

### CODE REVIEW

**Comment by manabuishii** [comment]
I think not only test with 0 byte files but also at least one file has more than 0 to confirm body of file is successfully available.

**Comment by mr-c** [comment]
@manabuishii I think we test for file availability in other conformance tests

**Comment by manabuishii** [comment]
OK I understand

**Comment by mr-c** [comment]
Jenkins, test this please

**Pull request merged**
