### PR TITLE
Specifying python2 as a python version for test scripts

### PR DESCRIPTION
**Pull request by StarvingMarvin**
There is an issue when executing conformance tests on machines where default python version isn't 2. args.py is simultaneously valid for 2 and 3, so that is left unchanged.

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, add to test list

**Comment by mr-c** [comment]
Jenkins, okay to test

**Comment by mr-c** [comment]
@StarvingMarvin This passes on `cwltool` but not Rabix. Shall we wait for you all to fix that or should I merge now?

**Comment by StarvingMarvin** [comment]
It seem there was an issue with Jenkins builds, tests pass for me both with current release and develop branch.

**Pull request merged**
