### PR TITLE
Add conformance test for empty writable dir

### PR DESCRIPTION
**Pull request by tetron**

### CODE REVIEW

**Comment by tetron** [comment]
For cwltool to pass this test is blocked on https://github.com/common-workflow-language/cwltool/pull/311

**Comment by StarvingMarvin** [comment]
Related bunny issue: https://github.com/rabix/bunny/issues/201

**Comment by mr-c** [comment]
- [ ] clarify the subject of every imperative sentences: for each sentence, is this the user's job or the implementation's job?

**Comment by mr-c** [comment]
@tetron can this be closed?

**Comment by tetron** [comment]
Merged into #410

**Pull request closed without merging**
