### PR TITLE
Lots of corner cases tests

### PR DESCRIPTION
**Pull request by mr-c**
Found bugs in both cwltool and toil-cwl-runner

### CODE REVIEW

**Comment by mr-c** [comment]
Jenkins, test cwlexec please

**Comment by mr-c** [comment]
`cwltool` passes these new test; with https://github.com/BD2KGenomics/toil/pull/2218 `toil-cwl-runner` will as well.

**Comment by mr-c** [comment]
Heads up to @milos-ljubinkovic as Rabix doesn't like any of the new Directory literal tests

**Comment by jmchilton** [comment]
Going to push a rebased version of this with labels and IDs, but as backup here is the original version: https://github.com/jmchilton/common-workflow-language/tree/extra_tests_prerebase.

**Pull request merged**
